version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DB_POSTGRES_NAME=postgres
      - DB_POSTGRES_USER=postgres
      - DB_POSTGRES_PASSWORD=postgres
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - SMTP_EMAIL_HOST=smtp4dev
      - SMTP_EMAIL_HOST_USER=''
      - SMTP_EMAIL_HOST_PASSWORD=''
      - SMTP_EMAIL_PORT=25
    volumes:
      - ./server:/usr/src/app/server
    depends_on:
      - postgres
    

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/client/node_modules
      - ./client:/usr/src/app/client
    environment:
      CHOKIDAR_USEPOLLING: "true"
      

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - 3030:80
    restart: always